Pr branch
araslav/books-store-project pull request #1
Opened 2024-01-04 22:52 UTC by araslav

2024-01-05 09:23 UTC, Sanderfuck requested changes

2024-01-05 09:23 UTC, Sanderfuck commented on src/main/java/book/store/repository/BookRepository.java
> +    List<Book> findAll();
Why do you need this methods, lets check methods from JPA repository

2024-01-05 09:23 UTC, Sanderfuck commented on src/main/java/book/store/service/impl/BookServiceImpl.java
> +    }
You can use @RequiredArgsConstructor instead of this

2024-01-10 15:44 UTC, kerrrusha approved these changes

2024-01-15 09:21 UTC, merged